application:
  hooks:
    pre-app-deploy: ./hooks/pre-app-deploy.js
    post-app-deploy: ./hooks/post-app-deploy.js
  runtimeManifest:
    packages:
      starter-kit:
        license: Apache-2.0
        actions:
          # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
          info:
            function: actions/starter-kit-info/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
              OAUTH_CLIENT_SECRET: $OAUTH_CLIENT_SECRET
              OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
              OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
              OAUTH_ORG_ID: $OAUTH_ORG_ID
              OAUTH_SCOPES: $OAUTH_SCOPES
              AIO_CLI_ENV: $AIO_CLI_ENV
            annotations:
              require-adobe-auth: true
              final: true
      #  ingestion:
      #    license: Apache-2.0
      #    actions:
      #      $include: ./actions/ingestion/actions.config.yaml
      webhook:
        license: Apache-2.0
        actions:
          $include: ./actions/webhook/actions.config.yaml
      product-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/product/commerce/actions.config.yaml
      product-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/product/external/actions.config.yaml
      customer-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/customer/commerce/actions.config.yaml
      customer-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/customer/external/actions.config.yaml
      order-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/order/commerce/actions.config.yaml
      order-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/order/external/actions.config.yaml
      stock-commerce:
        license: Apache-2.0
        actions:
          $include: ./actions/stock/commerce/actions.config.yaml
      stock-backoffice:
        license: Apache-2.0
        actions:
          $include: ./actions/stock/external/actions.config.yaml
  events:
    registrations:
      Backoffice Product Sync:
        description: Consumes product events from 3rd party systems
        events_of_interest:
          - provider_metadata: 3rd_party_custom_events
            event_codes:
              - be-observer.catalog_product_create
              - be-observer.catalog_product_update
              - be-observer.catalog_product_delete
        runtime_action: product-backoffice/consumer
      Backoffice Customer Sync:
        description: Consumes customer events from 3rd party systems
        events_of_interest:
          - provider_metadata: 3rd_party_custom_events
            event_codes:
              - be-observer.customer_create
              - be-observer.customer_update
              - be-observer.customer_delete
              - be-observer.customer_group_create
              - be-observer.customer_group_update
              - be-observer.customer_group_delete
        runtime_action: customer-backoffice/consumer
      Backoffice Order Sync:
        description: Consumes customer events from 3rd party systems
        events_of_interest:
          - provider_metadata: 3rd_party_custom_events
            event_codes:
              - be-observer.sales_order_status_update
              - be-observer.sales_order_shipment_create
              - be-observer.sales_order_shipment_update
        runtime_action: order-backoffice/consumer
      Backoffice Stock Sync:
        description: Consumes customer events from 3rd party systems
        events_of_interest:
          - provider_metadata: 3rd_party_custom_events
            event_codes:
              - be-observer.catalog_stock_update
        runtime_action: stock-backoffice/consumer
      Commerce Customer Sync:
        description: Consumes customer events from Adobe Commerce
        events_of_interest:
          - provider_metadata: dx_commerce_events
            event_codes:
              - com.adobe.commerce.<EVENT_PREFIX>.observer.customer_save_commit_after
              - com.adobe.commerce.<EVENT_PREFIX>.observer.customer_delete_commit_after
              - com.adobe.commerce.<EVENT_PREFIX>.observer.customer_group_save_commit_after
              - com.adobe.commerce.<EVENT_PREFIX>.observer.customer_group_delete_commit_after
        runtime_action: customer-commerce/consumer
      Commerce Product Sync:
        description: Consumes product events from Adobe Commerce
        events_of_interest:
          - provider_metadata: dx_commerce_events
            event_codes:
              - com.adobe.commerce.<EVENT_PREFIX>.observer.catalog_product_delete_commit_after
              - com.adobe.commerce.<EVENT_PREFIX>.observer.catalog_product_save_commit_after
        runtime_action: product-commerce/consumer
      Commerce Order Sync:
        description: Consumes order events from Adobe Commerce
        events_of_interest:
          - provider_metadata: dx_commerce_events
            event_codes:
              - com.adobe.commerce.<EVENT_PREFIX>.observer.sales_order_save_commit_after
        runtime_action: order-commerce/consumer
      Commerce Stock Sync:
        description: Consumes stock events from Adobe Commerce
        events_of_interest:
          - provider_metadata: dx_commerce_events
            event_codes:
              - com.adobe.commerce.<EVENT_PREFIX>.observer.cataloginventory_stock_item_save_commit_after
        runtime_action: stock-commerce/consumer
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
